In [1]:
# task 1

import numpy as np

print("========== TASK 1 ==========")

arr = np.random.randint(1, 51, 15)

print("Array:", arr)
print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Min:", arr.min())
print("Max:", arr.max())
print("Standard Deviation:", arr.std())


========== TASK 1 ==========
Array: [20 30 31 45 17  3 38 37 36 15 20 41 22 31 22]
Sum: 408
Mean: 27.2
Min: 3
Max: 45
Standard Deviation: 11.046568094510922


In [2]:
print("\n========== TASK 2 ==========")

matrix = np.random.randint(1, 10, (4, 4))

print("Matrix:\n", matrix)

det = np.linalg.det(matrix)
print("Determinant:", det)

print("Transpose:\n", matrix.T)


========== TASK 2 ==========
Matrix:
 [[3 7 1 4]
 [7 2 8 4]
 [1 1 8 1]
 [7 8 5 4]]
Determinant: 680.9999999999998
Transpose:
 [[3 7 1 7]
 [7 2 1 8]
 [1 8 8 5]
 [4 4 1 4]]


In [3]:
print("\n========== TASK 3 ==========")

numbers = np.random.randint(1, 100, 10)

print("Original Array:", numbers)

shuffled = numbers.copy()
np.random.shuffle(shuffled)

print("Shuffled Array:", shuffled)


========== TASK 3 ==========
Original Array: [67  5 48 37 35 18 90 52 69 82]
Shuffled Array: [67 69 18  5 35 82 52 48 37 90]
