In [ ]:
import numpy as np

def task1():
    arr = np.random.randint(1,51, size=15)
    print("Main Array Task 1:", arr)
    
    sum = np.sum(arr)
    mean = np.mean(arr)
    min = np.min(arr)
    max = np.max(arr)
    std = np.std(arr)
    
    print(f"Sum: {sum}")
    print(f"Mean: {mean:.2f}")
    print(f"Min: {min}")
    print(f"Max: {max}")
    print(f"Standard deviation: {std:.2f}")

def task2():
    arr = np.array([[1, 2, 3, 7],
                    [0, 1, 4, 9],
                    [5, 6, 16, 12],
                    [6, 2, 8, 1]
                    ])
    print("Main Array Task 2:\n", arr)
    
    determ = np.linalg.det(arr)
    print(f"determ: {determ:.2f}")
    
    print(f"\ntranspose:\n{arr.T}")

    invArr = np.linalg.inv(arr)
    print(f"\ninverse:\n{invArr}")
    

def task3():
    arr = np.random.randint(1, 101, size=10)
    
    shuffled_array = arr.copy()
    np.random.shuffle(shuffled_array)
    print("shuffle:", shuffled_array)
    
    print(f"original array:", arr)
    
    
def main():
    print("----- Task 1 -----")
    task1()
    print("\n----- Task 2 -----")
    task2()
    print("\n----- Task 3 -----")
    task3()

main()

In [7]:
# Practice
import numpy as np

# Practice 1
arr = np.array([1,2,3,4,5,6,7,8,9,10])
mean = np.mean(arr)

median = np.median(arr)

standard = np.std(arr)

# print(f"Array : {arr}")
# print(f"Mean : {mean}")
# print(f"Median : {median}")
# print(f"standard : {standard}")


# Practice 2
matrix = np.matrix([
    [10,5,12],
    [4,2,3],
    [8,1,7]
])


tran = np.transpose(matrix)
deter = np.linalg.det(matrix)
inv = np.linalg.inv(matrix)
print(f"tran: {tran}")
print(f"deter: {deter}")
print(f"inv: {inv}")

tran: [[10  4  8]
 [ 5  2  1]
 [12  3  7]]
deter: -54.00000000000006
inv: [[-0.2037037   0.42592593  0.16666667]
 [ 0.07407407  0.48148148 -0.33333333]
 [ 0.22222222 -0.55555556 -0.        ]]
