In [ ]:
import numpy as np

def task1():
    arr = np.random.randint(1,51, size=15)
    print("Main Array Task 1:", arr)
    
    sum = np.sum(arr)
    mean = np.mean(arr)
    min = np.min(arr)
    max = np.max(arr)
    std = np.std(arr)
    
    print(f"Sum: {sum}")
    print(f"Mean: {mean:.2f}")
    print(f"Min: {min}")
    print(f"Max: {max}")
    print(f"Standard deviation: {std:.2f}")

def task2():
    arr = np.array([[1, 2, 3, 7],
                    [0, 1, 4, 9],
                    [5, 6, 16, 12],
                    [6, 2, 8, 1]
                    ])
    print("Main Array Task 2:\n", arr)
    
    determ = np.linalg.det(arr)
    print(f"determ: {determ:.2f}")
    
    print(f"\ntranspose:\n{arr.T}")

    invArr = np.linalg.inv(arr)
    print(f"\ninverse:\n{invArr}")
    

def task3():
    arr = np.random.randint(1, 101, size=10)
    
    shuffled_array = arr.copy()
    np.random.shuffle(shuffled_array)
    print("shuffle:", shuffled_array)
    
    print(f"original array:", arr)
    
    
def main():
    print("----- Task 1 -----")
    task1()
    print("\n----- Task 2 -----")
    task2()
    print("\n----- Task 3 -----")
    task3()

main()

----- Task 1 -----
Main Array Task 1: [ 8 32 22 22 29 21 15 50 43 11 33 28 11 42 42]
Sum: 409
Mean: 27.27
Min: 8
Max: 50
Standard deviation: 12.66

----- Task 2 -----
Main Array Task 2:
 [[ 1  2  3  7]
 [ 0  1  4  9]
 [ 5  6 16 12]
 [ 6  2  8  1]]
determ: 443.00

transpose:
[[ 1  0  5  6]
 [ 2  1  6  2]
 [ 3  4 16  8]
 [ 7  9 12  1]]

inverse:
[[ 0.30699774 -0.01354402 -0.19187359  0.27539503]
 [ 0.53273138 -0.61173815  0.16704289 -0.22799097]
 [-0.37697517  0.1489842   0.11060948 -0.02934537]
 [ 0.10835214  0.11286682 -0.06772009  0.03837472]]

----- Task 3 -----
shuffle: [13  3  9 55 41 99 12 27 24 44]
original array: [44  3 99 27 13 12 41  9 55 24]

Comparison:
Index      Original        Shuffled       
----------------------------------------
0          44              13             
1          3               3              
2          99              9              
3          27              55             
4          13              41             
5          12              9