In [1]:
# =========== practice 1 ============ 
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])

mean_val = np.mean(arr)
median_val = np.median(arr)
std_val = np.std(arr)

print("Array:", arr)
print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143


In [ ]:
# =========== practice 2 ============ 

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 10]
])

transpose = matrix.T
determinant = np.linalg.det(matrix)

print("Matrix:\n", matrix)
print("\nTranspose:\n", transpose)
print("\nDeterminant:", determinant)

if determinant != 0:
    inverse = np.linalg.inv(matrix)
    print("\nInverse:\n", inverse)
else:
    print("\nInverse: Not possible (determinant = 0)")

Matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]

Transpose:
 [[ 1  4  7]
 [ 2  5  8]
 [ 3  6 10]]

Determinant: -2.9999999999999996

Inverse:
 [[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [3]:
# =========== practice 3 ============ 

nums = np.random.rand(5)
np.random.shuffle(nums)

print("Shuffled random numbers:", nums)

Shuffled random numbers: [0.19376386 0.28702852 0.27494066 0.97850985 0.34475504]


In [4]:
# =========== practice 4 ============ 

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]


In [3]:
# =========== practice 5 ============ 
import numpy as np

A = np.array([[1, 2],[3, 4]])

B = np.array([[2, 0],[1, 2]])

dot_product = np.dot(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Dot Product (A @ B):\n", dot_product)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[2 0]
 [1 2]]
Dot Product (A @ B):
 [[ 4  4]
 [10  8]]
